### ISSUE TITLE
Crashed the system

### ISSUE THREAD

**Issue by raffaelemancuso** [c0ldplasma/gnome-shell-extension-taskbar#39] opened 2021-05-05 23:14 UTC
I installed this extensions from extensions.gnome.org

The exact moment I clicked on the slide bar to install the extension my system crashed.
The system went to console (but without prompt) and I had to manually reboot it by pressing the power button.

I'm on Fedora 34 with GNOME 40

**Comment by c0ldplasma** [comment] 2021-05-06 06:28
Duplicate of #37

**Closed as completed by c0ldplasma** 2021-05-06 06:28 UTC
Labels: duplicate
